package lee.bright.sql4j.ql;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Bright Lee
 */
public enum TokenType {
	
	_COMMENT_("_COMMENT_"),
	
	_ID_("_ID_"),
	_NUM_("_NUM_"),
	_STR_("_STR_"),
	_PARAM_("_PARAM_"),

	_AMPERSAND_("&"),
	_ASTERISK_("*"),
	_CIRCUMFLEX_("^"),
	_COLON_(":"),
	_COMMA_(","),
	_CONCATENATION_OPERATOR_("||"),
	_DOUBLE_COLON_("::"),
	_DOUBLE_PERIOD_(".."),
	_DOUBLE_QUOTE_("\""),
	_EQUALS_OPERATOR_("="),
	_GREATER_THAN_OPERATOR_(">"),
	_GREATER_THAN_OR_EQUALS_OPERATOR_(">="),
	_LEFT_BRACE_("{"),
	_LEFT_BRACKET_("["),
	_LEFT_PAREN_("("),
	_LESS_THAN_OPERATOR_("<"),
	_LESS_THAN_OR_EQUALS_OPERATOR_("<="),
	_MINUS_SIGN_("-"),
	_NOT_EQUALS_OPERATOR_("<>"),
	_PERCENT_("%"),
	_PERIOD_("."),
	_PLUS_SIGN_("+"),
	_QUESTION_MARK_("?"),
	_QUOTE_("'"),
	_RIGHT_ARROW_("->"),
	_RIGHT_BRACE_("}"),
	_RIGHT_BRACKET_("]"),
	_RIGHT_PAREN_(")"),
	_SEMICOLON_(";"),
	_SOLIDUS_("/"),
	_UNDERSCORE_("_"),
	_VERTICAL_BAR_("|"),
	
	ADD("ADD"),
	ALL("ALL"),
	ALLOCATE("ALLOCATE"),
	ALTER("ALTER"),
	AND("AND"),
	ANY("ANY"),
	ARE("ARE"),
	ARRAY("ARRAY"),
	AS("AS"),
	ASENSITIVE("ASENSITIVE"),
	AT("AT"),
	ATOMIC("ATOMIC"),
	AUTHORIZATION("AUTHORIZATION"),
	BEGIN("BEGIN"),
	BETWEEN("BETWEEN"),
	BIGINT("BIGINT"),
	BINARY("BINARY"),
	BLOB("BLOB"),
	BOOLEAN("BOOLEAN"),
	BOTH("BOTH"),
	BY("BY"),
	CALL("CALL"),
	CALLED("CALLED"),
	CASCADED("CASCADED"),
	CASE("CASE"),
	CAST("CAST"),
	CHAR("CHAR"),
	CHARACTER("CHARACTER"),
	CHECK("CHECK"),
	CLOB("CLOB"),
	CLOSE("CLOSE"),
	COLLATE("COLLATE"),
	COLUMN("COLUMN"),
	COMMIT("COMMIT"),
	CONNECT("CONNECT"),
	CONSTRAINT("CONSTRAINT"),
	CONTINUE("CONTINUE"),
	CORRESPONDING("CORRESPONDING"),
	CREATE("CREATE"),
	CROSS("CROSS"),
	CUBE("CUBE"),
	CURRENT("CURRENT"),
	CURRENT_DATE("CURRENT_DATE"),
	CURRENT_DEFAULT_TRANSFORM_GROUP("CURRENT_DEFAULT_TRANSFORM_GROUP"),
	CURRENT_PATH("CURRENT_PATH"),
	CURRENT_ROLE("CURRENT_ROLE"),
	CURRENT_TIME("CURRENT_TIME"),
	CURRENT_TIMESTAMP("CURRENT_TIMESTAMP"),
	CURRENT_TRANSFORM_GROUP_FOR_TYPE("CURRENT_TRANSFORM_GROUP_FOR_TYPE"),
	CURRENT_USER("CURRENT_USER"),
	CURSOR("CURSOR"),
	CYCLE("CYCLE"),
	DATE("DATE"),
	DAY("DAY"),
	DEALLOCATE("DEALLOCATE"),
	DEC("DEC"),
	DECIMAL("DECIMAL"),
	DECLARE("DECLARE"),
	DEFAULT("DEFAULT"),
	DELETE("DELETE"),
	DEREF("DEREF"),
	DESCRIBE("DESCRIBE"),
	DETERMINISTIC("DETERMINISTIC"),
	DISCONNECT("DISCONNECT"),
	DISTINCT("DISTINCT"),
	DOUBLE("DOUBLE"),
	DROP("DROP"),
	DYNAMIC("DYNAMIC"),
	EACH("EACH"),
	ELEMENT("ELEMENT"),
	ELSE("ELSE"),
	END("END"),
	ESCAPE("ESCAPE"),
	EXCEPT("EXCEPT"),
	EXEC("EXEC"),
	EXECUTE("EXECUTE"),
	EXISTS("EXISTS"),
	EXTERNAL("EXTERNAL"),
	FALSE("FALSE"),
	FETCH("FETCH"),
	FILTER("FILTER"),
	FLOAT("FLOAT"),
	FOR("FOR"),
	FOREIGN("FOREIGN"),
	FREE("FREE"),
	FROM("FROM"),
	FULL("FULL"),
	FUNCTION("FUNCTION"),
	GET("GET"),
	GLOBAL("GLOBAL"),
	GRANT("GRANT"),
	GROUP("GROUP"),
	GROUPING("GROUPING"),
	HAVING("HAVING"),
	HOLD("HOLD"),
	HOUR("HOUR"),
	IDENTITY("IDENTITY"),
	IMMEDIATE("IMMEDIATE"),
	IN("IN"),
	INDEX("INDEX"),
	INDICATOR("INDICATOR"),
	INNER("INNER"),
	INOUT("INOUT"),
	INPUT("INPUT"),
	INSENSITIVE("INSENSITIVE"),
	INSERT("INSERT"),
	INT("INT"),
	INTEGER("INTEGER"),
	INTERSECT("INTERSECT"),
	INTERVAL("INTERVAL"),
	INTO("INTO"),
	IS("IS"),
	ISOLATION("ISOLATION"),
	JOIN("JOIN"),
	LANGUAGE("LANGUAGE"),
	LARGE("LARGE"),
	LATERAL("LATERAL"),
	LEADING("LEADING"),
	LEFT("LEFT"),
	LIKE("LIKE"),
	LOCAL("LOCAL"),
	LOCALTIME("LOCALTIME"),
	LOCALTIMESTAMP("LOCALTIMESTAMP"),
	MATCH("MATCH"),
	MEMBER("MEMBER"),
	MERGE("MERGE"),
	METHOD("METHOD"),
	MINUTE("MINUTE"),
	MODIFIES("MODIFIES"),
	MODIFY("MODIFY"),
	MODULE("MODULE"),
	MONTH("MONTH"),
	MULTISET("MULTISET"),
	NATIONAL("NATIONAL"),
	NATURAL("NATURAL"),
	NCHAR("NCHAR"),
	NCLOB("NCLOB"),
	NEW("NEW"),
	NO("NO"),
	NONE("NONE"),
	NOT("NOT"),
	NULL("NULL"),
	NUMERIC("NUMERIC"),
	OF("OF"),
	OLD("OLD"),
	ON("ON"),
	ONLY("ONLY"),
	OPEN("OPEN"),
	OR("OR"),
	ORDER("ORDER"),
	OUT("OUT"),
	OUTER("OUTER"),
	OUTPUT("OUTPUT"),
	OVER("OVER"),
	OVERLAPS("OVERLAPS"),
	PAGE("PAGE"),
	PARAMETER("PARAMETER"),
	PARTITION("PARTITION"),
	PRECISION("PRECISION"),
	PREPARE("PREPARE"),
	PRIMARY("PRIMARY"),
	PROCEDURE("PROCEDURE"),
	RANGE("RANGE"),
	READS("READS"),
	REAL("REAL"),
	RECURSIVE("RECURSIVE"),
	REF("REF"),
	REFERENCES("REFERENCES"),
	REFERENCING("REFERENCING"),
	RELEASE("RELEASE"),
	RETURN("RETURN"),
	RETURNS("RETURNS"),
	REVOKE("REVOKE"),
	RIGHT("RIGHT"),
	ROLLBACK("ROLLBACK"),
	ROLLUP("ROLLUP"),
	ROW("ROW"),
	ROWS("ROWS"),
	SAVEPOINT("SAVEPOINT"),
	SCROLL("SCROLL"),
	SEARCH("SEARCH"),
	SECOND("SECOND"),
	SELECT("SELECT"),
	SENSITIVE("SENSITIVE"),
	SESSION_USER("SESSION_USER"),
	SET("SET"),
	SIMILAR("SIMILAR"),
	SMALLINT("SMALLINT"),
	SOME("SOME"),
	SPECIFIC("SPECIFIC"),
	SPECIFICTYPE("SPECIFICTYPE"),
	SQL("SQL"),
	SQLEXCEPTION("SQLEXCEPTION"),
	SQLSTATE("SQLSTATE"),
	SQLWARNING("SQLWARNING"),
	START("START"),
	STATIC("STATIC"),
	SUBMULTISET("SUBMULTISET"),
	SYSTEM("SYSTEM"),
	SYSTEM_USER("SYSTEM_USER"),
	TABLE("TABLE"),
	THEN("THEN"),
	TIME("TIME"),
	TIMESTAMP("TIMESTAMP"),
	TIMEZONE_HOUR("TIMEZONE_HOUR"),
	TIMEZONE_MINUTE("TIMEZONE_MINUTE"),
	TO("TO"),
	TRAILING("TRAILING"),
	TRANSLATION("TRANSLATION"),
	TREAT("TREAT"),
	TRIGGER("TRIGGER"),
	TRUE("TRUE"),
	UNION("UNION"),
	UNIQUE("UNIQUE"),
	UNKNOWN("UNKNOWN"),
	UNNEST("UNNEST"),
	UPDATE("UPDATE"),
	USER("USER"),
	USING("USING"),
	VALUE("VALUE"),
	VALUES("VALUES"),
	VARCHAR("VARCHAR"),
	VARYING("VARYING"),
	WHEN("WHEN"),
	WHENEVER("WHENEVER"),
	WHERE("WHERE"),
	WINDOW("WINDOW"),
	WITH("WITH"),
	WITHIN("WITHIN"),
	WITHOUT("WITHOUT"),
	YEAR("YEAR");
	
	private static final Map<String, TokenType> TOKEN_TYPE_MAP = 
			new HashMap<String, TokenType>();
	
	static {
		TOKEN_TYPE_MAP.put(ADD.toString(), ADD);
		TOKEN_TYPE_MAP.put(ALL.toString(), ALL);
		TOKEN_TYPE_MAP.put(ALLOCATE.toString(), ALLOCATE);
		TOKEN_TYPE_MAP.put(ALTER.toString(), ALTER);
		TOKEN_TYPE_MAP.put(AND.toString(), AND);
		TOKEN_TYPE_MAP.put(ANY.toString(), ANY);
		TOKEN_TYPE_MAP.put(ARE.toString(), ARE);
		TOKEN_TYPE_MAP.put(ARRAY.toString(), ARRAY);
		TOKEN_TYPE_MAP.put(AS.toString(), AS);
		TOKEN_TYPE_MAP.put(ASENSITIVE.toString(), ASENSITIVE);
		TOKEN_TYPE_MAP.put(AT.toString(), AT);
		TOKEN_TYPE_MAP.put(ATOMIC.toString(), ATOMIC);
		TOKEN_TYPE_MAP.put(AUTHORIZATION.toString(), AUTHORIZATION);
		TOKEN_TYPE_MAP.put(BEGIN.toString(), BEGIN);
		TOKEN_TYPE_MAP.put(BETWEEN.toString(), BETWEEN);
		TOKEN_TYPE_MAP.put(BIGINT.toString(), BIGINT);
		TOKEN_TYPE_MAP.put(BINARY.toString(), BINARY);
		TOKEN_TYPE_MAP.put(BLOB.toString(), BLOB);
		TOKEN_TYPE_MAP.put(BOOLEAN.toString(), BOOLEAN);
		TOKEN_TYPE_MAP.put(BOTH.toString(), BOTH);
		TOKEN_TYPE_MAP.put(BY.toString(), BY);
		TOKEN_TYPE_MAP.put(CALL.toString(), CALL);
		TOKEN_TYPE_MAP.put(CALLED.toString(), CALLED);
		TOKEN_TYPE_MAP.put(CASCADED.toString(), CASCADED);
		TOKEN_TYPE_MAP.put(CASE.toString(), CASE);
		TOKEN_TYPE_MAP.put(CAST.toString(), CAST);
		TOKEN_TYPE_MAP.put(CHAR.toString(), CHAR);
		TOKEN_TYPE_MAP.put(CHARACTER.toString(), CHARACTER);
		TOKEN_TYPE_MAP.put(CHECK.toString(), CHECK);
		TOKEN_TYPE_MAP.put(CLOB.toString(), CLOB);
		TOKEN_TYPE_MAP.put(CLOSE.toString(), CLOSE);
		TOKEN_TYPE_MAP.put(COLLATE.toString(), COLLATE);
		TOKEN_TYPE_MAP.put(COLUMN.toString(), COLUMN);
		TOKEN_TYPE_MAP.put(COMMIT.toString(), COMMIT);
		TOKEN_TYPE_MAP.put(CONNECT.toString(), CONNECT);
		TOKEN_TYPE_MAP.put(CONSTRAINT.toString(), CONSTRAINT);
		TOKEN_TYPE_MAP.put(CONTINUE.toString(), CONTINUE);
		TOKEN_TYPE_MAP.put(CORRESPONDING.toString(), CORRESPONDING);
		TOKEN_TYPE_MAP.put(CREATE.toString(), CREATE);
		TOKEN_TYPE_MAP.put(CROSS.toString(), CROSS);
		TOKEN_TYPE_MAP.put(CUBE.toString(), CUBE);
		TOKEN_TYPE_MAP.put(CURRENT.toString(), CURRENT);
		TOKEN_TYPE_MAP.put(CURRENT_DATE.toString(), CURRENT_DATE);
		TOKEN_TYPE_MAP.put(CURRENT_DEFAULT_TRANSFORM_GROUP.toString(), CURRENT_DEFAULT_TRANSFORM_GROUP);
		TOKEN_TYPE_MAP.put(CURRENT_PATH.toString(), CURRENT_PATH);
		TOKEN_TYPE_MAP.put(CURRENT_ROLE.toString(), CURRENT_ROLE);
		TOKEN_TYPE_MAP.put(CURRENT_TIME.toString(), CURRENT_TIME);
		TOKEN_TYPE_MAP.put(CURRENT_TIMESTAMP.toString(), CURRENT_TIMESTAMP);
		TOKEN_TYPE_MAP.put(CURRENT_TRANSFORM_GROUP_FOR_TYPE.toString(), CURRENT_TRANSFORM_GROUP_FOR_TYPE);
		TOKEN_TYPE_MAP.put(CURRENT_USER.toString(), CURRENT_USER);
		TOKEN_TYPE_MAP.put(CURSOR.toString(), CURSOR);
		TOKEN_TYPE_MAP.put(CYCLE.toString(), CYCLE);
		TOKEN_TYPE_MAP.put(DATE.toString(), DATE);
		TOKEN_TYPE_MAP.put(DAY.toString(), DAY);
		TOKEN_TYPE_MAP.put(DEALLOCATE.toString(), DEALLOCATE);
		TOKEN_TYPE_MAP.put(DEC.toString(), DEC);
		TOKEN_TYPE_MAP.put(DECIMAL.toString(), DECIMAL);
		TOKEN_TYPE_MAP.put(DECLARE.toString(), DECLARE);
		TOKEN_TYPE_MAP.put(DEFAULT.toString(), DEFAULT);
		TOKEN_TYPE_MAP.put(DELETE.toString(), DELETE);
		TOKEN_TYPE_MAP.put(DEREF.toString(), DEREF);
		TOKEN_TYPE_MAP.put(DESCRIBE.toString(), DESCRIBE);
		TOKEN_TYPE_MAP.put(DETERMINISTIC.toString(), DETERMINISTIC);
		TOKEN_TYPE_MAP.put(DISCONNECT.toString(), DISCONNECT);
		TOKEN_TYPE_MAP.put(DISTINCT.toString(), DISTINCT);
		TOKEN_TYPE_MAP.put(DOUBLE.toString(), DOUBLE);
		TOKEN_TYPE_MAP.put(DROP.toString(), DROP);
		TOKEN_TYPE_MAP.put(DYNAMIC.toString(), DYNAMIC);
		TOKEN_TYPE_MAP.put(EACH.toString(), EACH);
		TOKEN_TYPE_MAP.put(ELEMENT.toString(), ELEMENT);
		TOKEN_TYPE_MAP.put(ELSE.toString(), ELSE);
		TOKEN_TYPE_MAP.put(END.toString(), END);
		TOKEN_TYPE_MAP.put(ESCAPE.toString(), ESCAPE);
		TOKEN_TYPE_MAP.put(EXCEPT.toString(), EXCEPT);
		TOKEN_TYPE_MAP.put(EXEC.toString(), EXEC);
		TOKEN_TYPE_MAP.put(EXECUTE.toString(), EXECUTE);
		TOKEN_TYPE_MAP.put(EXISTS.toString(), EXISTS);
		TOKEN_TYPE_MAP.put(EXTERNAL.toString(), EXTERNAL);
		TOKEN_TYPE_MAP.put(FALSE.toString(), FALSE);
		TOKEN_TYPE_MAP.put(FETCH.toString(), FETCH);
		TOKEN_TYPE_MAP.put(FILTER.toString(), FILTER);
		TOKEN_TYPE_MAP.put(FLOAT.toString(), FLOAT);
		TOKEN_TYPE_MAP.put(FOR.toString(), FOR);
		TOKEN_TYPE_MAP.put(FOREIGN.toString(), FOREIGN);
		TOKEN_TYPE_MAP.put(FREE.toString(), FREE);
		TOKEN_TYPE_MAP.put(FROM.toString(), FROM);
		TOKEN_TYPE_MAP.put(FULL.toString(), FULL);
		TOKEN_TYPE_MAP.put(FUNCTION.toString(), FUNCTION);
		TOKEN_TYPE_MAP.put(GET.toString(), GET);
		TOKEN_TYPE_MAP.put(GLOBAL.toString(), GLOBAL);
		TOKEN_TYPE_MAP.put(GRANT.toString(), GRANT);
		TOKEN_TYPE_MAP.put(GROUP.toString(), GROUP);
		TOKEN_TYPE_MAP.put(GROUPING.toString(), GROUPING);
		TOKEN_TYPE_MAP.put(HAVING.toString(), HAVING);
		TOKEN_TYPE_MAP.put(HOLD.toString(), HOLD);
		TOKEN_TYPE_MAP.put(HOUR.toString(), HOUR);
		TOKEN_TYPE_MAP.put(IDENTITY.toString(), IDENTITY);
		TOKEN_TYPE_MAP.put(IMMEDIATE.toString(), IMMEDIATE);
		TOKEN_TYPE_MAP.put(IN.toString(), IN);
		TOKEN_TYPE_MAP.put(INDEX.toString(), INDEX);
		TOKEN_TYPE_MAP.put(INDICATOR.toString(), INDICATOR);
		TOKEN_TYPE_MAP.put(INNER.toString(), INNER);
		TOKEN_TYPE_MAP.put(INOUT.toString(), INOUT);
		TOKEN_TYPE_MAP.put(INPUT.toString(), INPUT);
		TOKEN_TYPE_MAP.put(INSENSITIVE.toString(), INSENSITIVE);
		TOKEN_TYPE_MAP.put(INSERT.toString(), INSERT);
		TOKEN_TYPE_MAP.put(INT.toString(), INT);
		TOKEN_TYPE_MAP.put(INTEGER.toString(), INTEGER);
		TOKEN_TYPE_MAP.put(INTERSECT.toString(), INTERSECT);
		TOKEN_TYPE_MAP.put(INTERVAL.toString(), INTERVAL);
		TOKEN_TYPE_MAP.put(INTO.toString(), INTO);
		TOKEN_TYPE_MAP.put(IS.toString(), IS);
		TOKEN_TYPE_MAP.put(ISOLATION.toString(), ISOLATION);
		TOKEN_TYPE_MAP.put(JOIN.toString(), JOIN);
		TOKEN_TYPE_MAP.put(LANGUAGE.toString(), LANGUAGE);
		TOKEN_TYPE_MAP.put(LARGE.toString(), LARGE);
		TOKEN_TYPE_MAP.put(LATERAL.toString(), LATERAL);
		TOKEN_TYPE_MAP.put(LEADING.toString(), LEADING);
		TOKEN_TYPE_MAP.put(LEFT.toString(), LEFT);
		TOKEN_TYPE_MAP.put(LIKE.toString(), LIKE);
		TOKEN_TYPE_MAP.put(LOCAL.toString(), LOCAL);
		TOKEN_TYPE_MAP.put(LOCALTIME.toString(), LOCALTIME);
		TOKEN_TYPE_MAP.put(LOCALTIMESTAMP.toString(), LOCALTIMESTAMP);
		TOKEN_TYPE_MAP.put(MATCH.toString(), MATCH);
		TOKEN_TYPE_MAP.put(MEMBER.toString(), MEMBER);
		TOKEN_TYPE_MAP.put(MERGE.toString(), MERGE);
		TOKEN_TYPE_MAP.put(METHOD.toString(), METHOD);
		TOKEN_TYPE_MAP.put(MINUTE.toString(), MINUTE);
		TOKEN_TYPE_MAP.put(MODIFIES.toString(), MODIFIES);
		TOKEN_TYPE_MAP.put(MODIFY.toString(), MODIFY);
		TOKEN_TYPE_MAP.put(MODULE.toString(), MODULE);
		TOKEN_TYPE_MAP.put(MONTH.toString(), MONTH);
		TOKEN_TYPE_MAP.put(MULTISET.toString(), MULTISET);
		TOKEN_TYPE_MAP.put(NATIONAL.toString(), NATIONAL);
		TOKEN_TYPE_MAP.put(NATURAL.toString(), NATURAL);
		TOKEN_TYPE_MAP.put(NCHAR.toString(), NCHAR);
		TOKEN_TYPE_MAP.put(NCLOB.toString(), NCLOB);
		TOKEN_TYPE_MAP.put(NEW.toString(), NEW);
		TOKEN_TYPE_MAP.put(NO.toString(), NO);
		TOKEN_TYPE_MAP.put(NONE.toString(), NONE);
		TOKEN_TYPE_MAP.put(NOT.toString(), NOT);
		TOKEN_TYPE_MAP.put(NULL.toString(), NULL);
		TOKEN_TYPE_MAP.put(NUMERIC.toString(), NUMERIC);
		TOKEN_TYPE_MAP.put(OF.toString(), OF);
		TOKEN_TYPE_MAP.put(OLD.toString(), OLD);
		TOKEN_TYPE_MAP.put(ON.toString(), ON);
		TOKEN_TYPE_MAP.put(ONLY.toString(), ONLY);
		TOKEN_TYPE_MAP.put(OPEN.toString(), OPEN);
		TOKEN_TYPE_MAP.put(OR.toString(), OR);
		TOKEN_TYPE_MAP.put(ORDER.toString(), ORDER);
		TOKEN_TYPE_MAP.put(OUT.toString(), OUT);
		TOKEN_TYPE_MAP.put(OUTER.toString(), OUTER);
		TOKEN_TYPE_MAP.put(OUTPUT.toString(), OUTPUT);
		TOKEN_TYPE_MAP.put(OVER.toString(), OVER);
		TOKEN_TYPE_MAP.put(OVERLAPS.toString(), OVERLAPS);
		TOKEN_TYPE_MAP.put(PAGE.toString(), PAGE);
		TOKEN_TYPE_MAP.put(PARAMETER.toString(), PARAMETER);
		TOKEN_TYPE_MAP.put(PARTITION.toString(), PARTITION);
		TOKEN_TYPE_MAP.put(PRECISION.toString(), PRECISION);
		TOKEN_TYPE_MAP.put(PREPARE.toString(), PREPARE);
		TOKEN_TYPE_MAP.put(PRIMARY.toString(), PRIMARY);
		TOKEN_TYPE_MAP.put(PROCEDURE.toString(), PROCEDURE);
		TOKEN_TYPE_MAP.put(RANGE.toString(), RANGE);
		TOKEN_TYPE_MAP.put(READS.toString(), READS);
		TOKEN_TYPE_MAP.put(REAL.toString(), REAL);
		TOKEN_TYPE_MAP.put(RECURSIVE.toString(), RECURSIVE);
		TOKEN_TYPE_MAP.put(REF.toString(), REF);
		TOKEN_TYPE_MAP.put(REFERENCES.toString(), REFERENCES);
		TOKEN_TYPE_MAP.put(REFERENCING.toString(), REFERENCING);
		TOKEN_TYPE_MAP.put(RELEASE.toString(), RELEASE);
		TOKEN_TYPE_MAP.put(RETURN.toString(), RETURN);
		TOKEN_TYPE_MAP.put(RETURNS.toString(), RETURNS);
		TOKEN_TYPE_MAP.put(REVOKE.toString(), REVOKE);
		TOKEN_TYPE_MAP.put(RIGHT.toString(), RIGHT);
		TOKEN_TYPE_MAP.put(ROLLBACK.toString(), ROLLBACK);
		TOKEN_TYPE_MAP.put(ROLLUP.toString(), ROLLUP);
		TOKEN_TYPE_MAP.put(ROW.toString(), ROW);
		TOKEN_TYPE_MAP.put(ROWS.toString(), ROWS);
		TOKEN_TYPE_MAP.put(SAVEPOINT.toString(), SAVEPOINT);
		TOKEN_TYPE_MAP.put(SCROLL.toString(), SCROLL);
		TOKEN_TYPE_MAP.put(SEARCH.toString(), SEARCH);
		TOKEN_TYPE_MAP.put(SECOND.toString(), SECOND);
		TOKEN_TYPE_MAP.put(SELECT.toString(), SELECT);
		TOKEN_TYPE_MAP.put(SENSITIVE.toString(), SENSITIVE);
		TOKEN_TYPE_MAP.put(SESSION_USER.toString(), SESSION_USER);
		TOKEN_TYPE_MAP.put(SET.toString(), SET);
		TOKEN_TYPE_MAP.put(SIMILAR.toString(), SIMILAR);
		TOKEN_TYPE_MAP.put(SMALLINT.toString(), SMALLINT);
		TOKEN_TYPE_MAP.put(SOME.toString(), SOME);
		TOKEN_TYPE_MAP.put(SPECIFIC.toString(), SPECIFIC);
		TOKEN_TYPE_MAP.put(SPECIFICTYPE.toString(), SPECIFICTYPE);
		TOKEN_TYPE_MAP.put(SQL.toString(), SQL);
		TOKEN_TYPE_MAP.put(SQLEXCEPTION.toString(), SQLEXCEPTION);
		TOKEN_TYPE_MAP.put(SQLSTATE.toString(), SQLSTATE);
		TOKEN_TYPE_MAP.put(SQLWARNING.toString(), SQLWARNING);
		TOKEN_TYPE_MAP.put(START.toString(), START);
		TOKEN_TYPE_MAP.put(STATIC.toString(), STATIC);
		TOKEN_TYPE_MAP.put(SUBMULTISET.toString(), SUBMULTISET);
		TOKEN_TYPE_MAP.put(SYSTEM.toString(), SYSTEM);
		TOKEN_TYPE_MAP.put(SYSTEM_USER.toString(), SYSTEM_USER);
		TOKEN_TYPE_MAP.put(TABLE.toString(), TABLE);
		TOKEN_TYPE_MAP.put(THEN.toString(), THEN);
		TOKEN_TYPE_MAP.put(TIME.toString(), TIME);
		TOKEN_TYPE_MAP.put(TIMESTAMP.toString(), TIMESTAMP);
		TOKEN_TYPE_MAP.put(TIMEZONE_HOUR.toString(), TIMEZONE_HOUR);
		TOKEN_TYPE_MAP.put(TIMEZONE_MINUTE.toString(), TIMEZONE_MINUTE);
		TOKEN_TYPE_MAP.put(TO.toString(), TO);
		TOKEN_TYPE_MAP.put(TRAILING.toString(), TRAILING);
		TOKEN_TYPE_MAP.put(TRANSLATION.toString(), TRANSLATION);
		TOKEN_TYPE_MAP.put(TREAT.toString(), TREAT);
		TOKEN_TYPE_MAP.put(TRIGGER.toString(), TRIGGER);
		TOKEN_TYPE_MAP.put(TRUE.toString(), TRUE);
		TOKEN_TYPE_MAP.put(UNION.toString(), UNION);
		TOKEN_TYPE_MAP.put(UNIQUE.toString(), UNIQUE);
		TOKEN_TYPE_MAP.put(UNKNOWN.toString(), UNKNOWN);
		TOKEN_TYPE_MAP.put(UNNEST.toString(), UNNEST);
		TOKEN_TYPE_MAP.put(UPDATE.toString(), UPDATE);
		TOKEN_TYPE_MAP.put(USER.toString(), USER);
		TOKEN_TYPE_MAP.put(USING.toString(), USING);
		TOKEN_TYPE_MAP.put(VALUE.toString(), VALUE);
		TOKEN_TYPE_MAP.put(VALUES.toString(), VALUES);
		TOKEN_TYPE_MAP.put(VARCHAR.toString(), VARCHAR);
		TOKEN_TYPE_MAP.put(VARYING.toString(), VARYING);
		TOKEN_TYPE_MAP.put(WHEN.toString(), WHEN);
		TOKEN_TYPE_MAP.put(WHENEVER.toString(), WHENEVER);
		TOKEN_TYPE_MAP.put(WHERE.toString(), WHERE);
		TOKEN_TYPE_MAP.put(WINDOW.toString(), WINDOW);
		TOKEN_TYPE_MAP.put(WITH.toString(), WITH);
		TOKEN_TYPE_MAP.put(WITHIN.toString(), WITHIN);
		TOKEN_TYPE_MAP.put(WITHOUT.toString(), WITHOUT);
		TOKEN_TYPE_MAP.put(YEAR.toString(), YEAR);
	}
	
	public static TokenType getTokenType(String content) {
		TokenType tokenType = TOKEN_TYPE_MAP.get(
				content.toUpperCase());
		return tokenType;
	}
	
	private String content;
	
	TokenType(String content) {
		this.content = content;
	}
	
	@Override
	public String toString() {
		return content;
	}

}
